  

spring:
  devtools:
    livereload:
      enabled: true
  
  datasource:
    url:  jdbc:mysql://localhost:3306/adcampaign?useSSL=true
    username : root
    password : mahadev12
    driverClassName : com.mysql.jdbc.Driver
    
    
    

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        strategy:  org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
      

    

    

    

   
    
       